#!/bin/bash

yum -y install mysql mysql-server
service mysqld start

mysqladmin -u root password password
yum install -y mysql-connector-java
ambari-server setup --jdbc-db=mysql --jdbc-driver=/usr/share/java/mysql-connector-java.jar

ambari-server install-mpack --mpack=https://github.com/amerissa/cloudbreak-hdf-druid/raw/master/www/hdf-ambari-mpack-3.0.3.0-6.tar.gz
